-- Set up QuickBite Dev Schema
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Drop existing tables
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAYMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE OUTBOX_EVENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RESTAURANTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    phone VARCHAR2(20),
    role VARCHAR2(20) CHECK (role IN ('CUSTOMER', 'RIDER', 'RESTAURANT', 'ADMIN', 'SYNC_JOB')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RESTAURANTS (
    restaurant_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id NUMBER REFERENCES USERS(user_id),
    name VARCHAR2(100) NOT NULL,
    city_zone VARCHAR2(50) NOT NULL,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDERS (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER REFERENCES USERS(user_id),
  restaurant_id NUMBER REFERENCES RESTAURANTS(restaurant_id),
  rider_id NUMBER REFERENCES USERS(user_id),
  status VARCHAR2(20) DEFAULT 'PLACED' CHECK (status IN ('PLACED', 'CONFIRMED', 'PREPARING', 'PACKED', 'WAITING_FOR_PICKUP', 'WAITING_CONFIRM', 'PICKED_UP', 'DELIVERED', 'CANCELLED')),
  total_amount NUMBER(10,2) NOT NULL,
  delivery_address VARCHAR2(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDER_ITEMS (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES ORDERS(order_id),
    item_name VARCHAR2(100) NOT NULL,
    quantity NUMBER NOT NULL,
    price NUMBER(10, 2) NOT NULL
);

CREATE TABLE PAYMENTS (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES ORDERS(order_id),
    amount NUMBER(10, 2) NOT NULL,
    payment_method VARCHAR2(20) CHECK (payment_method IN ('WALLET', 'CARD', 'CASH', 'UPI')),
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OUTBOX_EVENTS (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR2(50) NOT NULL,
    aggregate_id VARCHAR2(50) NOT NULL,
    event_type VARCHAR2(50) NOT NULL,
    payload CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_dispatched NUMBER(1) DEFAULT 0
);

CREATE TABLE AUDIT_LOG (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50) NOT NULL,
    record_id NUMBER NOT NULL,
    action VARCHAR2(20) NOT NULL,
    old_status VARCHAR2(20),
    new_status VARCHAR2(20),
    changed_by NUMBER REFERENCES USERS(user_id),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- T2: State Machine for Order Transitions
CREATE OR REPLACE PROCEDURE ORDER_STATE_MACHINE (
    p_order_id IN NUMBER,
    p_new_status IN VARCHAR2,
    p_changed_by IN NUMBER
) AS
    v_current_status VARCHAR2(20);
BEGIN
    SELECT status INTO v_current_status FROM ORDERS WHERE order_id = p_order_id FOR UPDATE;
    
    IF v_current_status = 'PLACED' AND p_new_status IN ('CONFIRMED', 'CANCELLED') THEN
        UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
    ELSIF v_current_status = 'CONFIRMED' AND p_new_status IN ('PREPARING', 'CANCELLED') THEN
        UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
    ELSIF v_current_status = 'PREPARING' AND p_new_status IN ('PACKED', 'CANCELLED') THEN
        UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
    ELSIF v_current_status = 'PACKED' AND p_new_status IN ('WAITING_FOR_PICKUP', 'WAITING_CONFIRM', 'CANCELLED') THEN
        UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
    ELSIF v_current_status = 'WAITING_FOR_PICKUP' AND p_new_status IN ('WAITING_CONFIRM', 'PICKED_UP', 'CANCELLED') THEN
        UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
    ELSIF v_current_status = 'WAITING_CONFIRM' AND p_new_status IN ('WAITING_FOR_PICKUP', 'PICKED_UP', 'CANCELLED') THEN
        UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
    ELSIF v_current_status = 'PICKED_UP' AND p_new_status = 'DELIVERED' THEN
        UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Invalid state transition from ' || v_current_status || ' to ' || p_new_status);
    END IF;
    
    INSERT INTO AUDIT_LOG (table_name, record_id, action, old_status, new_status, changed_by)
    VALUES ('ORDERS', p_order_id, 'STATUS_CHANGE', v_current_status, p_new_status, p_changed_by);
END;
/

-- Trigger for Automatic Audit & Outbox on Order Update
CREATE OR REPLACE TRIGGER trg_order_status_change
AFTER UPDATE OF status ON ORDERS
FOR EACH ROW
BEGIN
    IF :OLD.status != :NEW.status THEN
        INSERT INTO OUTBOX_EVENTS (aggregate_type, aggregate_id, event_type, payload)
        VALUES (
            'ORDER', 
            TO_CHAR(:NEW.order_id), 
            'ORDER_STATUS_CHANGED', 
            '{"order_id": ' || :NEW.order_id || ', "old_status": "' || :OLD.status || '", "new_status": "' || :NEW.status || '"}'
        );
    END IF;
END;
/

-- Insert Seed Data (Pakistan)
INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Admin', 'admin@quickbite.pk', '$2b$12$abc123hashed', 'ADMIN');

INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Customer Ali', 'ali@quickbite.pk', '$2b$12$abc123hashed', 'CUSTOMER');
INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Customer Sana', 'sana@quickbite.pk', '$2b$12$abc123hashed', 'CUSTOMER');

INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Rider Hamza', 'hamza@quickbite.pk', '$2b$12$abc123hashed', 'RIDER');
INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Rider Bilal', 'bilal@quickbite.pk', '$2b$12$abc123hashed', 'RIDER');

INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Namal Cafe Owner', 'namal@quickbite.pk', '$2b$12$abc123hashed', 'RESTAURANT');
INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Pizza Corner Owner', 'pizza@quickbite.pk', '$2b$12$abc123hashed', 'RESTAURANT');
INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Bundu Khan Owner', 'bundu@quickbite.pk', '$2b$12$abc123hashed', 'RESTAURANT');
INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Rahat Bakers Owner', 'rahat@quickbite.pk', '$2b$12$abc123hashed', 'RESTAURANT');
INSERT INTO USERS (full_name, email, password_hash, role)
VALUES ('Monal Owner', 'monal@quickbite.pk', '$2b$12$abc123hashed', 'RESTAURANT');

INSERT INTO RESTAURANTS (owner_id, name, city_zone) VALUES (6, 'Namal Cafe', 'Mianwali-Central');
INSERT INTO RESTAURANTS (owner_id, name, city_zone) VALUES (7, 'Pizza Corner', 'Mianwali-Central');
INSERT INTO RESTAURANTS (owner_id, name, city_zone) VALUES (8, 'Bundu Khan', 'Lahore-Gulberg');
INSERT INTO RESTAURANTS (owner_id, name, city_zone) VALUES (9, 'Rahat Bakers', 'Lahore-DHA');
INSERT INTO RESTAURANTS (owner_id, name, city_zone) VALUES (10, 'Monal', 'Islamabad-F7');

COMMIT;