
/* Drop existing check constraint */
ALTER TABLE ORDERS DROP CONSTRAINT ORDER_STATUS_CHECK;

/* Add new check constraint with all statuses */
ALTER TABLE ORDERS ADD CONSTRAINT ORDER_STATUS_CHECK CHECK (
    status IN ('PLACED', 'CONFIRMED', 'PREPARING', 'PACKED', 'WAITING_FOR_PICKUP', 'WAITING_CONFIRM', 'PICKED_UP', 'DELIVERED', 'CANCELLED')
);
