const { getConnection } = require('../db/oracle');
const { connectMongo, mongoose } = require('../db/mongo');
const bcrypt = require('bcryptjs');
require('dotenv').config();

async function initOracle() {
  console.log('--- Initializing Oracle Database ---');
  let conn;
  try {
    conn = await getConnection();

    // Check if tables exist, if not create them
    try {
      await conn.execute(`
        CREATE TABLE USERS (
          user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          full_name VARCHAR2(100) NOT NULL,
          email VARCHAR2(100) UNIQUE NOT NULL,
          password_hash VARCHAR2(255) NOT NULL,
          phone VARCHAR2(20),
          role VARCHAR2(20) CHECK (role IN ('CUSTOMER', 'RIDER', 'RESTAURANT', 'ADMIN', 'SYNC_JOB')),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `);
      console.log('Created USERS table');
    } catch (e) {
      console.log('USERS table already exists');
    }

    try {
      await conn.execute(`
        CREATE TABLE RESTAURANTS (
          restaurant_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id NUMBER REFERENCES USERS(user_id),
          name VARCHAR2(100) NOT NULL,
          city_zone VARCHAR2(50) NOT NULL,
          is_active NUMBER(1) DEFAULT 1,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `);
      console.log('Created RESTAURANTS table');
    } catch (e) {
      console.log('RESTAURANTS table already exists');
    }

    try {
      await conn.execute(`
        CREATE TABLE ORDERS (
          order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          customer_id NUMBER REFERENCES USERS(user_id),
          restaurant_id NUMBER REFERENCES RESTAURANTS(restaurant_id),
          rider_id NUMBER REFERENCES USERS(user_id),
          status VARCHAR2(20) DEFAULT 'PLACED' CHECK (status IN ('PLACED', 'CONFIRMED', 'PREPARING', 'PICKED_UP', 'DELIVERED', 'CANCELLED')),
          total_amount NUMBER(10, 2) NOT NULL,
          delivery_address VARCHAR2(255),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `);
      console.log('Created ORDERS table');
    } catch (e) {
      console.log('ORDERS table already exists');
    }

    try {
      await conn.execute(`
        CREATE TABLE ORDER_ITEMS (
          item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id NUMBER REFERENCES ORDERS(order_id),
          item_name VARCHAR2(100) NOT NULL,
          quantity NUMBER NOT NULL,
          price NUMBER(10, 2) NOT NULL
        )
      `);
      console.log('Created ORDER_ITEMS table');
    } catch (e) {
      console.log('ORDER_ITEMS table already exists');
    }

    try {
      await conn.execute(`
        CREATE TABLE PAYMENTS (
          payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id NUMBER REFERENCES ORDERS(order_id),
          amount NUMBER(10, 2) NOT NULL,
          payment_method VARCHAR2(20) CHECK (payment_method IN ('WALLET', 'CARD', 'CASH', 'UPI')),
          status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `);
      console.log('Created PAYMENTS table');
    } catch (e) {
      console.log('PAYMENTS table already exists');
    }

    try {
      await conn.execute(`
        CREATE TABLE OUTBOX_EVENTS (
          event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          aggregate_type VARCHAR2(50) NOT NULL,
          aggregate_id VARCHAR2(50) NOT NULL,
          event_type VARCHAR2(50) NOT NULL,
          payload CLOB NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          is_dispatched NUMBER(1) DEFAULT 0
        )
      `);
      console.log('Created OUTBOX_EVENTS table');
    } catch (e) {
      console.log('OUTBOX_EVENTS table already exists');
    }

    try {
      await conn.execute(`
        CREATE TABLE AUDIT_LOG (
          audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          table_name VARCHAR2(50) NOT NULL,
          record_id NUMBER NOT NULL,
          action VARCHAR2(20) NOT NULL,
          old_status VARCHAR2(20),
          new_status VARCHAR2(20),
          changed_by NUMBER REFERENCES USERS(user_id),
          timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `);
      console.log('Created AUDIT_LOG table');
    } catch (e) {
      console.log('AUDIT_LOG table already exists');
    }

    // Create State Machine Procedure
    try {
      await conn.execute(`
        CREATE OR REPLACE PROCEDURE ORDER_STATE_MACHINE (
          p_order_id IN NUMBER,
          p_new_status IN VARCHAR2,
          p_changed_by IN NUMBER
        ) AS
          v_current_status VARCHAR2(20);
        BEGIN
          SELECT status INTO v_current_status FROM ORDERS WHERE order_id = p_order_id FOR UPDATE;
          
          IF v_current_status = 'PLACED' AND p_new_status IN ('CONFIRMED', 'CANCELLED') THEN
            UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
          ELSIF v_current_status = 'CONFIRMED' AND p_new_status = 'PREPARING' THEN
            UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
          ELSIF v_current_status = 'PREPARING' AND p_new_status = 'PICKED_UP' THEN
            UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
          ELSIF v_current_status = 'PICKED_UP' AND p_new_status = 'DELIVERED' THEN
            UPDATE ORDERS SET status = p_new_status WHERE order_id = p_order_id;
          ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Invalid state transition from ' || v_current_status || ' to ' || p_new_status);
          END IF;
          
          INSERT INTO AUDIT_LOG (table_name, record_id, action, old_status, new_status, changed_by)
          VALUES ('ORDERS', p_order_id, 'STATUS_CHANGE', v_current_status, p_new_status, p_changed_by);
        END;
      `);
      console.log('Created ORDER_STATE_MACHINE procedure');
    } catch (e) {
      console.log('ORDER_STATE_MACHINE procedure already exists');
    }

    // Create Trigger
    try {
      await conn.execute(`
        CREATE OR REPLACE TRIGGER trg_order_status_change
        AFTER UPDATE OF status ON ORDERS
        FOR EACH ROW
        BEGIN
          IF :OLD.status != :NEW.status THEN
            INSERT INTO OUTBOX_EVENTS (aggregate_type, aggregate_id, event_type, payload)
            VALUES (
              'ORDER', 
              TO_CHAR(:NEW.order_id), 
              'ORDER_STATUS_CHANGED', 
              '{"order_id": ' || :NEW.order_id || ', "old_status": "' || :OLD.status || '", "new_status": "' || :NEW.status || '"}'
            );
          END IF;
        END;
      `);
      console.log('Created trg_order_status_change trigger');
    } catch (e) {
      console.log('trg_order_status_change trigger already exists');
    }

    // Insert Seed Data
    const passwordHash = await bcrypt.hash('password123', 10);

    // Check if users exist
    const existingUsers = await conn.execute(`SELECT COUNT(*) as count FROM USERS`);
    if (existingUsers.rows[0].COUNT === 0) {
      console.log('Inserting seed users...');
      
      await conn.execute(
        `INSERT INTO USERS (full_name, email, password_hash, role) VALUES (:1, :2, :3, :4)`,
        ['Admin User', 'admin@quickbite.pk', passwordHash, 'ADMIN'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO USERS (full_name, email, password_hash, role) VALUES (:1, :2, :3, :4)`,
        ['Customer Ali', 'ali@quickbite.pk', passwordHash, 'CUSTOMER'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO USERS (full_name, email, password_hash, role) VALUES (:1, :2, :3, :4)`,
        ['Customer Sana', 'sana@quickbite.pk', passwordHash, 'CUSTOMER'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO USERS (full_name, email, password_hash, role) VALUES (:1, :2, :3, :4)`,
        ['Rider Hamza', 'hamza@quickbite.pk', passwordHash, 'RIDER'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO USERS (full_name, email, password_hash, role) VALUES (:1, :2, :3, :4)`,
        ['Rider Bilal', 'bilal@quickbite.pk', passwordHash, 'RIDER'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO USERS (full_name, email, password_hash, role) VALUES (:1, :2, :3, :4)`,
        ['Namal Cafe Owner', 'namal@quickbite.pk', passwordHash, 'RESTAURANT'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO USERS (full_name, email, password_hash, role) VALUES (:1, :2, :3, :4)`,
        ['Pizza Corner Owner', 'pizza@quickbite.pk', passwordHash, 'RESTAURANT'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO USERS (full_name, email, password_hash, role) VALUES (:1, :2, :3, :4)`,
        ['Bundu Khan Owner', 'bundu@quickbite.pk', passwordHash, 'RESTAURANT'],
        { autoCommit: true }
      );
      
      console.log('Inserted seed users');

      // Insert Restaurants
      await conn.execute(
        `INSERT INTO RESTAURANTS (owner_id, name, city_zone) VALUES (:1, :2, :3)`,
        [6, 'Namal Cafe', 'Mianwali-Central'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO RESTAURANTS (owner_id, name, city_zone) VALUES (:1, :2, :3)`,
        [7, 'Pizza Corner', 'Mianwali-Central'],
        { autoCommit: true }
      );
      
      await conn.execute(
        `INSERT INTO RESTAURANTS (owner_id, name, city_zone) VALUES (:1, :2, :3)`,
        [8, 'Bundu Khan', 'Lahore-Gulberg'],
        { autoCommit: true }
      );
      
      console.log('Inserted seed restaurants');
    } else {
      console.log('Seed data already exists');
    }

    console.log('Oracle initialization completed successfully');
  } catch (err) {
    console.error('Oracle initialization error:', err);
    throw err;
  } finally {
    if (conn) await conn.close();
  }
}

async function initMongo() {
  console.log('\n--- Initializing MongoDB ---');
  try {
    await connectMongo();
    const db = mongoose.connection.db;

    // Create collections with indexes
    const restaurants = db.collection('restaurants');
    await restaurants.createIndex({ oracle_rest_id: 1 }, { unique: true });
    await restaurants.createIndex({ location: '2dsphere' });
    await restaurants.createIndex({ city_zone: 1, cuisine: 1, is_active: 1 });
    console.log('Created restaurants collection with indexes');

    const riderlocations = db.collection('riderlocations');
    await riderlocations.createIndex({ location: '2dsphere' });
    await riderlocations.createIndex({ timestamp: 1 }, { expireAfterSeconds: 172800 }); // 48 hours TTL
    console.log('Created riderlocations collection with indexes');

    const orderhistory = db.collection('orderhistory');
    await orderhistory.createIndex({ oracle_order_id: 1 }, { unique: true });
    console.log('Created orderhistory collection with indexes');

    const eta_estimates = db.collection('eta_estimates');
    await eta_estimates.createIndex({ restaurant_id: 1, hour_of_day: 1 });
    console.log('Created eta_estimates collection with indexes');

    const chats = db.collection('chats');
    await chats.createIndex({ order_id: 1 });
    console.log('Created chats collection with indexes');

    const notifications = db.collection('notifications');
    await notifications.createIndex({ user_id: 1, is_read: 1 });
    console.log('Created notifications collection with indexes');

    const reviews = db.collection('reviews');
    await reviews.createIndex({ restaurant_id: 1 });
    console.log('Created reviews collection with indexes');

    // Insert sample restaurant data
    const existingRestaurants = await restaurants.countDocuments();
    if (existingRestaurants === 0) {
      console.log('Inserting sample restaurants...');
      await restaurants.insertMany([
        {
          oracle_restaurant_id: 1,
          name: 'Namal Cafe',
          city_zone: 'Mianwali-Central',
          location: { type: 'Point', coordinates: [71.8234, 32.5967] },
          cuisine: ['Pakistani', 'Fast Food'],
          menu: [
            { name: 'Biryani', price: 350, category: 'Main', available: true, description: 'Aromatic basmati rice with spiced meat' },
            { name: 'Chai', price: 60, category: 'Drinks', available: true, description: 'Traditional Pakistani tea' },
            { name: 'Paratha', price: 80, category: 'Breakfast', available: true, description: 'Flaky flatbread' },
            { name: 'Karahi', price: 550, category: 'Main', available: true, description: 'Spiced chicken curry' },
            { name: 'Seekh Kebab', price: 400, category: 'Starters', available: true, description: 'Grilled spiced minced meat' }
          ],
          avg_rating: 4.5,
          is_active: true,
          opening_hours: { open: '07:00', close: '23:00' }
        },
        {
          oracle_restaurant_id: 2,
          name: 'Pizza Corner',
          city_zone: 'Mianwali-Central',
          location: { type: 'Point', coordinates: [71.8100, 32.5900] },
          cuisine: ['Italian', 'Fast Food'],
          menu: [
            { name: 'Margherita', price: 800, category: 'Pizza', available: true, description: 'Classic tomato and cheese pizza' },
            { name: 'Pepsi', price: 80, category: 'Drinks', available: true, description: 'Cold soft drink' },
            { name: 'Garlic Bread', price: 150, category: 'Sides', available: true, description: 'Buttery garlic bread' },
            { name: 'Chicken Fajita', price: 950, category: 'Pizza', available: true, description: 'Spicy chicken with peppers' }
          ],
          avg_rating: 4.2,
          is_active: true,
          opening_hours: { open: '12:00', close: '01:00' }
        },
        {
          oracle_restaurant_id: 3,
          name: 'Bundu Khan',
          city_zone: 'Lahore-Gulberg',
          location: { type: 'Point', coordinates: [74.3587, 31.5122] },
          cuisine: ['Pakistani', 'BBQ'],
          menu: [
            { name: 'Seekh Kebab', price: 450, category: 'BBQ', available: true, description: 'Traditional seekh kebabs' },
            { name: 'Naan', price: 30, category: 'Sides', available: true, description: 'Fresh tandoori naan' },
            { name: 'Lassi', price: 120, category: 'Drinks', available: true, description: 'Sweet yogurt drink' },
            { name: 'Malai Boti', price: 550, category: 'BBQ', available: true, description: 'Creamy chicken tikka' }
          ],
          avg_rating: 4.7,
          is_active: true,
          opening_hours: { open: '11:00', close: '00:00' }
        }
      ]);
      console.log('Inserted sample restaurants');
    } else {
      console.log('Sample restaurants already exist');
    }

    // Insert sample rider locations
    const riders = db.collection('riderlocations');
    const existingRiders = await riders.countDocuments();
    if (existingRiders === 0) {
      console.log('Inserting sample rider locations...');
      await riders.insertMany([
        {
          oracle_rider_id: 4,
          status: 'AVAILABLE',
          location: { type: 'Point', coordinates: [71.8250, 32.5980] },
          city_zone: 'Mianwali-Central',
          timestamp: new Date()
        },
        {
          oracle_rider_id: 5,
          status: 'AVAILABLE',
          location: { type: 'Point', coordinates: [71.8200, 32.5950] },
          city_zone: 'Mianwali-Central',
          timestamp: new Date()
        }
      ]);
      console.log('Inserted sample rider locations');
    } else {
      console.log('Sample rider locations already exist');
    }

    console.log('MongoDB initialization completed successfully');
  } catch (err) {
    console.error('MongoDB initialization error:', err);
    throw err;
  }
}

async function initAll() {
  try {
    await initOracle();
    await initMongo();
    console.log('\n=== Database Initialization Complete ===');
    console.log('Default credentials:');
    console.log('Admin: admin@quickbite.pk / password123');
    console.log('Customer: ali@quickbite.pk / password123');
    console.log('Rider: hamza@quickbite.pk / password123');
    console.log('Restaurant: namal@quickbite.pk / password123');
    process.exit(0);
  } catch (err) {
    console.error('Initialization failed:', err);
    process.exit(1);
  }
}

initAll();
