-- Add RIDER_EARNINGS table to track individual earnings records per order
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RIDER_EARNINGS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE RIDER_EARNINGS (
    earning_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES ORDERS(order_id) UNIQUE, -- Unique to prevent duplicates (idempotency key)
    rider_id NUMBER REFERENCES USERS(user_id),
    order_total NUMBER(10,2) NOT NULL,
    earning_amount NUMBER(10,2) NOT NULL, -- 10% of order total by default
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Optional: Add index on rider_id and created_at for faster history queries
CREATE INDEX idx_rider_earnings_rider ON RIDER_EARNINGS(rider_id);
CREATE INDEX idx_rider_earnings_order ON RIDER_EARNINGS(order_id);

COMMIT;
